### PR TITLE
READMEs and dataset generation files. 

### PR DESCRIPTION
**Pull request by SchndrSrh**

### CODE REVIEW

**Comment by PatrickFeeney** [comment]
Could you add a commit to remove the code folder? Those Python files won't run when in our repository and I think the stuff in the code README is covered in the READMEs for each dataset. Everything else looks great!

**Comment by SchndrSrh** [comment]
Okay, sure. Can you run the original repository files now? The “dataset READMEs” are a little bit more
detailed. Anyway, it’s probably better to combine them to one single file anyway.

Best,
Sarah


Von: Patrick Feeney <notifications@github.com>
Gesendet: Montag, 22. Februar 2021 17:16
An: tufts-ai-robotics-group/polycraft-novelty-data <polycraft-novelty-data@noreply.github.com>
Cc: Schneider Sarah <Sarah.Schneider@ait.ac.at>; Author <author@noreply.github.com>
Betreff: Re: [tufts-ai-robotics-group/polycraft-novelty-data] READMEs and dataset generation files. (#2)


Could you add a commit to remove the code folder? Those Python files won't run when in our repository and I think the stuff in the code README is covered in the READMEs for each dataset. Everything else looks great!

**Comment by PatrickFeeney** [comment]
If you made a change to your fork after my earlier comment, it looks like it hasn't been pushed to GitHub. Are you making any changes to the Polycraft files? If not, it's fine to just link to where they are in the other repository instead of having multiple copies. If so, are you making any changes that need to be separate from the Polycraft repo? Or could you just push the changes?

**Comment by SchndrSrh** [comment]
Hi Patrick,

I removed the code folder and pushed it to my fork right now.


Von: PatrickFeeney <notifications@github.com>
Gesendet: Montag, 22. Februar 2021 22:31
An: tufts-ai-robotics-group/polycraft-novelty-data <polycraft-novelty-data@noreply.github.com>
Cc: Schneider Sarah <Sarah.Schneider@ait.ac.at>; Author <author@noreply.github.com>
Betreff: Re: [tufts-ai-robotics-group/polycraft-novelty-data] READMEs and dataset generation files. (#2)


If you made a change to your fork after my earlier comment, it looks like it hasn't been pushed to GitHub. Are you making any changes to the Polycraft files? If not, it's fine to just link to where they are in the other repository instead of having multiple copies. If so, are you making any changes that need to be separate from the Polycraft repo? Or could you just push the changes?

**Pull request merged**
